image:
  tag: 1.0.6
specs: eslint nuxt oxlint oxlint-tsgolint pinia pixi.js playwright prettier rolldown tailwindcss tsdown typescript vite vitest vue
cronTime: 0 */30 * * * *
discordWebhookId: "1410572127786242130"
extraObjects:
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: npm-version-notifier
      namespace: npm-version-notifier
    spec:
      encryptedData:
        discordWebhookToken: AgAq+JKF4axRhh4QFyGNLTQpdyq11Jtr9G6f9l0W2clK/DJxkFpbeOw8DdPee37w0kwk9GMwYw4uoueOXj2xUOupekdizRbxYX+fo2rj8vRXGoNeieBdUHN3D70s4MupODf8AcxCIuf3e1wX+6MuFKIGCx2jS6suP5KPZTBnVOCaFcGH9WHLKCVgVN5f1I6ylJtaDD8OHgPmkvvmEqyf/oG0X1LWhlwREpkSllopMNVHN2NOdqCm/RxCskKY3nQxxe9aBnZupGWOrWyNReckcrpTRJ4ds1MGMmkBF5N9d18h+DBmgHynVQtT5IJZi/qqCz9/L9ai6OFU4hZnV+vcHPS9BG3UgB+KfnPDPW1zgIFdVv+d6QGVjk2MCXtASQAgZwnj7Ydj7PIQn4l172dyHYm+cYj977+snjUQoRdT1s5kfwfkfbxdM/VXhJbb6R5AK6vJv4fPI9V6YencGlljPG0bJ7T9r1KcMLpuW0FU5uIowlC0dgFllwUMDkesg1rLEGitsGFVe1wRRaQSWJL1/sI+FSPYhnuEugObC/kxAxhfD4kKHyURHxQZj+dg4D1k5elzl68TUtm76OKXSSfye8rFsjXPMAvbXNNHTJ80r0Aw9M62vzZ0KJxUp43h5HE/1slsoVhODKEhjXyZOeRyV73qx4ZSciCakpEzX0vbxo7ZwrC+WINUeyCIzq9c5tbRPEESeaAECJ6BCdC+v3bOCF99w6hQoh+hP/O/VnCgaLbi5bvSPQ5vFEK7clax/xMMitZSIBTF68FTJXUQe04+j0+BvNgZSg==
        githubToken: AgBi31r9gljI8mCyFNOSz404410YoBDwzC2U/wnbuRHWfannoHm/ZVmOyJIsq4CCsbNglQD7FP2GFPFoa8rCDAhGePOg4V/8gWzwD6Tc3immjo54M90YQ3n6sZm5USahBj7VrdSIlQLENultVaZHzWdHbRH+8PsieWBGfBgH4Z/Pno+15jpIm+gRkiPJmhhPledAhlnN6B/oJSuCJdKJS1LLMwZt5Riql1sWMwxA6fae+71ZWf5rEqG8drGlJb4kNP7N6d2LJu/gJd/UBOyd7C6i3qoCaTtSP6KhGvREP4ECHgKTiaBTRKQvsLaBvQz8vUzit52W/zQi3voftbH2SKq+LZ+CvtLKArPSlGYXz8aCOcGBJeV8SYfwn9n5KFW7du5XRTFzD4+j4UYYCy3Cijlf6Zxk302D2zYy0I/HxBB+lQGg3zFYxs0tbLMJpJRdo9qLMVKEI0InJrik9LkU862HYqoCXiz0efxEe3UMvpau+MO8PBeybYpIMUfD5LwYu/FLXQBWbw5ZRgirn2tF5CxNytGwdMCGACI8MjFLGn6S9C+oEA1zLll8IM0n0RGAkCYxZFhs+96aTHCDq37KwysDWdWPNmEUhr+VxtVi6zPKn+ldsH19ioWEDLwVR0Z97sQPDXraBInffqYEffQqT7JKKao0YIBNKkJJG9D73Z7R3w4OBNkVGXIKeNIt2OiBD+MhzIM7hhTOvVluMvf/XmXPKXRv44heGwhcC2JwZ2lVHRvJywRpzRztddcF2m6V6NIpETzw9OutkS2JXQ1D26RPLOt4JlQuCJ8rTh7aTaHZ4mh/+b5AJODudJOCuVs=
      template:
        metadata:
          creationTimestamp: null
          name: npm-version-notifier
          namespace: npm-version-notifier
